// Generated by gencpp from file px4_offboard/JoyCommand.msg
// DO NOT EDIT!


#ifndef PX4_OFFBOARD_MESSAGE_JOYCOMMAND_H
#define PX4_OFFBOARD_MESSAGE_JOYCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Quaternion.h>

namespace px4_offboard
{
template <class ContainerAllocator>
struct JoyCommand_
{
  typedef JoyCommand_<ContainerAllocator> Type;

  JoyCommand_()
    : header()
    , position()
    , yaw(0.0)
    , orientation()
    , failsafe(false)
    , arm(false)
    , offboard(false)
    , takeoff(false)
    , land(false)  {
    }
  JoyCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , yaw(0.0)
    , orientation(_alloc)
    , failsafe(false)
    , arm(false)
    , offboard(false)
    , takeoff(false)
    , land(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef uint8_t _failsafe_type;
  _failsafe_type failsafe;

   typedef uint8_t _arm_type;
  _arm_type arm;

   typedef uint8_t _offboard_type;
  _offboard_type offboard;

   typedef uint8_t _takeoff_type;
  _takeoff_type takeoff;

   typedef uint8_t _land_type;
  _land_type land;




  typedef boost::shared_ptr< ::px4_offboard::JoyCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_offboard::JoyCommand_<ContainerAllocator> const> ConstPtr;

}; // struct JoyCommand_

typedef ::px4_offboard::JoyCommand_<std::allocator<void> > JoyCommand;

typedef boost::shared_ptr< ::px4_offboard::JoyCommand > JoyCommandPtr;
typedef boost::shared_ptr< ::px4_offboard::JoyCommand const> JoyCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_offboard::JoyCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_offboard::JoyCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace px4_offboard

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'px4_offboard': ['/home/tuofeichen/SLAM/MAV-Project/px4_ws/src/px4_offboard/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::px4_offboard::JoyCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_offboard::JoyCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_offboard::JoyCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_offboard::JoyCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_offboard::JoyCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_offboard::JoyCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_offboard::JoyCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ff5c348546b7bfead04686358bc531d";
  }

  static const char* value(const ::px4_offboard::JoyCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ff5c348546b7bfeULL;
  static const uint64_t static_value2 = 0xad04686358bc531dULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_offboard::JoyCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_offboard/JoyCommand";
  }

  static const char* value(const ::px4_offboard::JoyCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_offboard::JoyCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Point position\n\
float64 yaw\n\
geometry_msgs/Quaternion orientation\n\
bool failsafe\n\
bool arm \n\
bool offboard\n\
bool takeoff\n\
bool  land\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::px4_offboard::JoyCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_offboard::JoyCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.yaw);
      stream.next(m.orientation);
      stream.next(m.failsafe);
      stream.next(m.arm);
      stream.next(m.offboard);
      stream.next(m.takeoff);
      stream.next(m.land);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct JoyCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_offboard::JoyCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_offboard::JoyCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "failsafe: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.failsafe);
    s << indent << "arm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arm);
    s << indent << "offboard: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.offboard);
    s << indent << "takeoff: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.takeoff);
    s << indent << "land: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.land);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_OFFBOARD_MESSAGE_JOYCOMMAND_H
