# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_offboard/JoyCommand.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class JoyCommand(genpy.Message):
  _md5sum = "dee1f7c5569586cf7ca47c22ff97902c"
  _type = "px4_offboard/JoyCommand"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
geometry_msgs/Point position
float64 yaw
geometry_msgs/Quaternion orientation
bool failsafe
bool arm 
bool offboard
bool takeoff
bool land
byte autostate
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','position','yaw','orientation','failsafe','arm','offboard','takeoff','land','autostate']
  _slot_types = ['std_msgs/Header','geometry_msgs/Point','float64','geometry_msgs/Quaternion','bool','bool','bool','bool','bool','byte']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,position,yaw,orientation,failsafe,arm,offboard,takeoff,land,autostate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JoyCommand, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.yaw is None:
        self.yaw = 0.
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      if self.failsafe is None:
        self.failsafe = False
      if self.arm is None:
        self.arm = False
      if self.offboard is None:
        self.offboard = False
      if self.takeoff is None:
        self.takeoff = False
      if self.land is None:
        self.land = False
      if self.autostate is None:
        self.autostate = 0
    else:
      self.header = std_msgs.msg.Header()
      self.position = geometry_msgs.msg.Point()
      self.yaw = 0.
      self.orientation = geometry_msgs.msg.Quaternion()
      self.failsafe = False
      self.arm = False
      self.offboard = False
      self.takeoff = False
      self.land = False
      self.autostate = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_8d5Bb.pack(_x.position.x, _x.position.y, _x.position.z, _x.yaw, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.failsafe, _x.arm, _x.offboard, _x.takeoff, _x.land, _x.autostate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 70
      (_x.position.x, _x.position.y, _x.position.z, _x.yaw, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.failsafe, _x.arm, _x.offboard, _x.takeoff, _x.land, _x.autostate,) = _struct_8d5Bb.unpack(str[start:end])
      self.failsafe = bool(self.failsafe)
      self.arm = bool(self.arm)
      self.offboard = bool(self.offboard)
      self.takeoff = bool(self.takeoff)
      self.land = bool(self.land)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_8d5Bb.pack(_x.position.x, _x.position.y, _x.position.z, _x.yaw, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.failsafe, _x.arm, _x.offboard, _x.takeoff, _x.land, _x.autostate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 70
      (_x.position.x, _x.position.y, _x.position.z, _x.yaw, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.failsafe, _x.arm, _x.offboard, _x.takeoff, _x.land, _x.autostate,) = _struct_8d5Bb.unpack(str[start:end])
      self.failsafe = bool(self.failsafe)
      self.arm = bool(self.arm)
      self.offboard = bool(self.offboard)
      self.takeoff = bool(self.takeoff)
      self.land = bool(self.land)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_8d5Bb = struct.Struct("<8d5Bb")
