// Generated by gencpp from file px4_offboard/MoveCommand.msg
// DO NOT EDIT!


#ifndef PX4_OFFBOARD_MESSAGE_MOVECOMMAND_H
#define PX4_OFFBOARD_MESSAGE_MOVECOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace px4_offboard
{
template <class ContainerAllocator>
struct MoveCommand_
{
  typedef MoveCommand_<ContainerAllocator> Type;

  MoveCommand_()
    : header()
    , distance(0.0)
    , code(0)  {
    }
  MoveCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance(0.0)
    , code(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _distance_type;
  _distance_type distance;

   typedef int32_t _code_type;
  _code_type code;




  typedef boost::shared_ptr< ::px4_offboard::MoveCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_offboard::MoveCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MoveCommand_

typedef ::px4_offboard::MoveCommand_<std::allocator<void> > MoveCommand;

typedef boost::shared_ptr< ::px4_offboard::MoveCommand > MoveCommandPtr;
typedef boost::shared_ptr< ::px4_offboard::MoveCommand const> MoveCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_offboard::MoveCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_offboard::MoveCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace px4_offboard

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'px4_offboard': ['/home/tuofeichen/SLAM/MAV-Project/catkin_ws/src/px4_offboard/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::px4_offboard::MoveCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_offboard::MoveCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_offboard::MoveCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_offboard::MoveCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_offboard::MoveCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_offboard::MoveCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_offboard::MoveCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9b934f688da69b3a0fce6b02d08ed62";
  }

  static const char* value(const ::px4_offboard::MoveCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9b934f688da69b3ULL;
  static const uint64_t static_value2 = 0xa0fce6b02d08ed62ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_offboard::MoveCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_offboard/MoveCommand";
  }

  static const char* value(const ::px4_offboard::MoveCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_offboard::MoveCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 distance\n\
int32 code\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::px4_offboard::MoveCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_offboard::MoveCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance);
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MoveCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_offboard::MoveCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_offboard::MoveCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_OFFBOARD_MESSAGE_MOVECOMMAND_H
